# Generated by Django 4.2 on 2025-02-04 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='dish',
        ),
        migrations.DeleteModel(
            name='Cooking',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
    ]
