# Generated by Django 4.2 on 2025-02-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
