# Generated by Django 4.2 on 2025-02-10 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='like',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cooking',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
