# Generated by Django 4.2 on 2025-02-10 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
