# Generated by Django 4.2 on 2025-02-12 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_notification_read'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bio',
        ),
    ]
